# permissions for end users to edit stacks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stack-editor-role
rules:
- apiGroups:
  - tf.tf-operator.io
  resources:
  - stacks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tf.tf-operator.io
  resources:
  - stacks/status
  verbs:
  - get
